version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/var/www/html
      - ./logs/nginx:/var/log/nginx
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.02'
          memory: 24M
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
        mode: "non-blocking"


  php-fpm:
    image: php:8.1-fpm
    volumes:
      - ./html:/var/www/html
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.02'
          memory: 24M
